project_name: platform
builds:
  - id: influx
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/influx/
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=xcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
      - MACOSX_DEPLOYMENT_TARGET=10.11
    ldflags: -s -w -X main.version=nightly -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: influx
  - id: influxd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/influxd/
    flags:
      - -tags=assets
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=xcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
      - MACOSX_DEPLOYMENT_TARGET=10.11
    ldflags: -s -w -X main.version=nightly -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: influxd
    hooks:
      pre: make generate

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_nightly_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

blobs:
  - provider: "s3"
    bucket: "dl.influxdata.com"
    region: "us-east-1"
    folder: "platform/nightlies/"

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - influxd
      - influx
    image_templates:
      - "quay.io/influxdb/influx:nightly"
    dockerfile: docker/influxd/Dockerfile
    extra_files:
      - docker/influxd/entrypoint.sh

# Do not make github release
release:
  disable: true
